version: 2

sphinx:
  builder: html
  configuration: didppy/docs/conf.py

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
    rust: "1.70"

python:
  install:
    - method: pip
      path: ./didppy
    - requirements: ./didppy/docs/requirements.txt
