[package]
name = "didp-yaml"
default-run = "didp-yaml"
version = "0.10.1"
edition = "2021"
rust-version = "1.85"
description = "YAML interface for Dynamic Programming Description Language (DyPDL) and DyPDL solvers."
license = "MIT OR Apache-2.0"
authors = [
    "Ryo Kuroiwa <kuroiwa@nii.ac.jp>",
    "Yuxiao (Jasper) Chen <yuxiao.chen@mail.utoronto.ca>",
    "Anubhav Singh <anubhav.singh@utoronto.ca>",
]
homepage = "https://didp.ai"
repository = "https://github.com/domain-independent-dp/didp-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dypdl = { path = "../dypdl", version = "0.10.1" }
dypdl-heuristic-search = { path = "../dypdl-heuristic-search", version = "0.10.1" }
rustc-hash = "2.1.2"
yaml-rust = { package = "yaml-rust2", version = "0.11.0" }
num-traits = "0.2.19"
lazy_static = "1.5.0"
approx = "0.5.1"
itertools = "0.14.0"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.6.1"
