name: dypdl

on:
  push:
    paths:
      - "dypdl/**"
      - "!**.md"
    branches:
      - main
      - develop
  pull_request:
    paths:
      - "dypdl/**"
      - "!**.md"
    branches:
      - main
      - develop

defaults:
  run:
    working-directory: dypdl

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [1.65.0, stable]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo test
