name: dypdl

on:
  push:
    paths:
      - "dypdl/**"
      - "!**.md"
    branches:
      - main
  pull_request:
    paths:
      - "dypdl/**"
      - "!**.md"
    branches:
      - main

defaults:
  run:
    working-directory: dypdl

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.64.0
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo test
